import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  body: string;
  category: 'culture' | 'science' | 'travel' | 'history' | 'weird' | 'tech';
  emoji: string;
  country?: string;
  readTime: number; // minutes
  publishedAt: number; // timestamp
  imageGradient: string;
}

const BLOG_POOL: Array<Omit<BlogPost, 'id' | 'publishedAt'>> = [
  { title: "Why Japan Has 3 Different Alphabets (And Uses All of Them at Once)", excerpt: "Hiragana, katakana, kanji — and sometimes romaji too. Here's why Japanese text looks like a beautiful puzzle.", body: "Japanese is unique in that it actively uses three different writing systems simultaneously — and often in the same sentence. Hiragana (ひらがな) handles native Japanese words and grammar. Katakana (カタカナ) is reserved for foreign loanwords and emphasis, while kanji (漢字) are Chinese-derived characters that carry meaning. A single menu at a Tokyo ramen shop might include all three in three words. The system evolved over centuries: kanji arrived via China, hiragana was developed by women in the Heian period as a more fluid script, and katakana was created by Buddhist monks. Far from being confusing, Japanese readers process all three automatically — a feat of cognitive flexibility that amazes linguists worldwide.", category: 'culture', emoji: '🇯🇵', country: 'Japan', readTime: 4, imageGradient: 'from-red-500/20 to-pink-600/20' },
  { title: "The Midnight Sun: Where the Sun Never Sets for 70 Days Straight", excerpt: "In northern Norway, the sun stays above the horizon for over two months. Here's what life is actually like.", body: "Above the Arctic Circle in places like Tromsø, Norway, the midnight sun is real — from late May to late July the sun simply doesn't go down. At 2am you can read a book outside without a lamp. Birds sing at midnight. Children play football at 11pm. The phenomenon is caused by Earth's axial tilt of 23.5 degrees: in summer, the North Pole tilts toward the sun so dramatically that polar regions receive continuous sunlight. Locals adapt with blackout curtains, sleep masks, and a relaxed attitude toward conventional sleeping hours. The flip side? In winter, these same towns experience polar night — no sun at all for weeks. The Sami people, indigenous to the region, have adapted culturally over millennia and have dozens of words for different types of Arctic light.", category: 'travel', emoji: '🌅', country: 'Norway', readTime: 5, imageGradient: 'from-orange-500/20 to-yellow-500/20' },
  { title: "The Town That Lives in a Permanent Time Paradox", excerpt: "Lijiang, China exists in a single timezone despite spanning the width of a continent. The result? Sunrise at 10am.", body: "China is geographically wide enough to span five natural time zones — from UTC+5 to UTC+9. But in 1949, the People's Republic decided to unify the entire country under a single timezone: Beijing Time (UTC+8). The result in western provinces like Xinjiang is surreal: the sun rises at 10am and sets past 10pm in summer. Office hours have quietly shifted — people eat lunch at 2pm and dinner at 9pm. In Xinjiang, the Uyghur minority often run on an unofficial 'Xinjiang time' two hours behind Beijing, creating a dual-timezone reality within the same city. This isn't unique to China — India uses one timezone too, creating a 90-minute offset at its western and eastern extremes. Time, it turns out, is deeply political.", category: 'weird', emoji: '⏰', country: 'China', readTime: 4, imageGradient: 'from-cyan-500/20 to-blue-600/20' },
  { title: "How Polynesians Navigated the Pacific With No Instruments", excerpt: "No compass, no GPS, no maps. Just stars, waves, and birds — and they found every island in the Pacific.", body: "The Polynesian voyagers who settled islands across 10 million square miles of the Pacific Ocean did so with a navigation system so sophisticated it still amazes scientists. Wayfinders read the stars — memorizing the rising and setting positions of hundreds of stars to construct a mental star compass. They felt the ocean swells with their bodies, detecting how major swells wrap around islands, creating 'swell shadows' detectable hundreds of miles away. Birds were tracked: certain species fly up to 40 miles from land each morning and return each evening, serving as living compasses. The shape of clouds, the color of water, and even the smell of vegetation guided them. This knowledge, nearly lost in the 20th century, is being actively revived by organizations like the Polynesian Voyaging Society, whose canoe Hōkūleʻa has circumnavigated the globe using only traditional navigation.", category: 'history', emoji: '🧭', country: 'Polynesia', readTime: 6, imageGradient: 'from-teal-500/20 to-cyan-600/20' },
  { title: "The Weird Science of Why 3pm Feels Slower Than 3am", excerpt: "Your brain literally experiences time differently depending on the hour — and science finally knows why.", body: "Time perception is not constant — your brain actively constructs the experience of time passing, and it does so differently depending on circadian phase, emotion, temperature, and even what you're doing. In the early afternoon, body temperature peaks and the brain's clock neurons fire most rapidly, making time feel like it drags. At 3am, when body temperature is at its lowest, subjective time collapses — minutes vanish. The dopamine system plays a huge role: when you're excited or deeply focused, dopamine causes internal clock pulses to speed up, making you underestimate elapsed time ('flow state'). Fear does the opposite — it slows perceived time, which is why near-misses seem to happen in slow motion. This isn't just psychological: different countries' work cultures exploit these rhythms naturally. Spain's siesta tradition, Japan's inemuri (socially acceptable public napping), and Scandinavia's early work start times are all aligned, consciously or not, with human chronobiology.", category: 'science', emoji: '🧠', readTime: 5, imageGradient: 'from-purple-500/20 to-indigo-600/20' },
  { title: "Iceland Has No Mosquitoes — Here's the Bizarre Reason Why", excerpt: "It's cold, it's wet, it has plenty of standing water. Mosquitoes should love it. But there are none. Science is baffled.", body: "Iceland is a mosquito-free paradise — a fact that seems impossible given that mosquitoes thrive in cold, wet environments across Scandinavia, Canada, and Russia, all of which share Iceland's climate. The leading theory involves Iceland's freeze-thaw cycles: mosquito larvae need consistently cold water that freezes and thaws on a predictable seasonal schedule to complete their life cycle. Iceland's weather is unusually variable even within a single season, disrupting larval development. A warm week in February can hatch larvae that then die in a March freeze. Another theory involves Iceland's unique geothermal activity — the water chemistry in naturally heated pools may be inhospitable to larvae. Whatever the reason, Icelanders enjoy outdoor summers blissfully free of the swarms that plague every neighboring country. Several other places share this status: the Faroe Islands, New Caledonia, and French Polynesia.", category: 'weird', emoji: '🦟', country: 'Iceland', readTime: 3, imageGradient: 'from-blue-500/20 to-cyan-500/20' },
  { title: "The Country That Invented the Weekend — And How It Spread to the World", excerpt: "The 5-day workweek isn't ancient wisdom. It was invented in 1908 in a New England cotton mill. Here's the full story.", body: "The modern weekend as we know it — two full days off on Saturday and Sunday — is surprisingly recent. Before the 20th century, the typical worker had only Sunday off, if that. The shift began in 1908 at a cotton mill in New England that wanted to accommodate its Jewish workers, who observed the Sabbath on Saturday. By giving Saturday off as well as Sunday, the mill inadvertently created the first secular two-day weekend. Henry Ford institutionalized it in 1926 when he switched Ford Motor Company to a 40-hour, 5-day work week — not out of generosity, but because he believed workers with leisure time would spend money on cars and consumer goods. The Great Depression pushed governments to codify the 40-hour week through legislation as a way to spread employment. The international labor organization standardized it globally by mid-century. Today, some countries are experimenting with 4-day weeks — the next evolution in a surprisingly short 116-year history.", category: 'history', emoji: '🎉', country: 'USA', readTime: 5, imageGradient: 'from-green-500/20 to-emerald-600/20' },
  { title: "Dubai Built an Indoor Ski Slope in the Desert — And It's Busier Than Most Mountain Resorts", excerpt: "Ski Dubai sits inside a mall in one of the hottest cities on Earth. 400 real tons of snow, real penguins, and 6,000 visitors a day.", body: "Ski Dubai opened in 2005 inside the Mall of the Emirates in a city where outdoor temperatures regularly hit 45°C (113°F). The facility maintains an indoor temperature of -1°C to -2°C year-round, houses five ski runs including a 400-meter black diamond slope, and uses real snow — about 30 tons of which are produced each night by snow cannon systems. The penguins (real South African penguins) live in a dedicated sub-zero habitat and come out to meet visitors twice daily. The facility uses roughly the same amount of energy as 1,500 homes — a fact that draws both admiration and criticism. But it's commercially successful: it attracts over 6,000 visitors on peak days and has inspired copycat indoor ski resorts across the Middle East and China. It's also bizarrely functional: Dubai's ski instructors are legitimately certified European coaches who moved to the desert for steady year-round work.", category: 'travel', emoji: '⛷️', country: 'UAE', readTime: 4, imageGradient: 'from-sky-500/20 to-blue-600/20' },
  { title: "The Voynich Manuscript: The 600-Year-Old Book Nobody Can Read", excerpt: "Discovered in 1912, carbon-dated to 1404, filled with mysterious illustrations and an unknown language. Still undeciphered.", body: "The Voynich Manuscript is a 240-page illustrated codex written in an unknown script that has defeated some of the world's best cryptographers, linguists, and AI systems for over a century. Carbon dating places its creation between 1404 and 1438. The illustrations depict unidentifiable plants, naked women in green pools connected by tubes, astronomical diagrams, and zodiac-like charts — all accompanied by flowing text in a script that has never been seen in any other document. It follows the statistical patterns of a real language (Zipf's Law, character frequency distributions) yet no one has ever matched it to any known or proposed language. The manuscript was purchased in 1912 by book dealer Wilfrid Voynich from an Italian castle. Theories range from an elaborate hoax to an extinct language to an alien document. In 2019, a Bristol academic claimed it was written in proto-Romance phonetic script — but the claim was swiftly disputed. It remains the most mysterious manuscript in existence.", category: 'history', emoji: '📜', readTime: 6, imageGradient: 'from-amber-500/20 to-orange-600/20' },
  { title: "Why South Korea Has the World's Fastest Internet — And How They Built It", excerpt: "Average speeds 10x faster than the US. It was a government decision made in 1994, and it changed everything.", body: "South Korea consistently tops global internet speed rankings — average download speeds exceed 250 Mbps, with many homes on gigabit fiber. The US averages around 230 Mbps, but Korea's consistency is the real achievement: 99.9% of the population has access to high-speed broadband. The story starts in 1994 when President Kim Young-sam declared the 'Information Superhighway' a national priority. The government subsidized fiber rollout and forced telecom competition by opening local loops to multiple providers. Crucially, Korea's high urban population density made fiber economics work: running a cable in Seoul reaches 20,000 households per kilometer vs. 200 in rural America. The cultural side helped too: PC bangs (internet cafés) created a national gaming culture in the late 1990s that demanded fast, reliable internet, which drove consumer expectations sky-high. The result is infrastructure that handles 8K streaming, real-time cloud gaming, and remote surgery with ease.", category: 'tech', emoji: '⚡', country: 'South Korea', readTime: 5, imageGradient: 'from-rose-500/20 to-pink-600/20' },
  { title: "The Country That Runs on 100% Renewable Energy (And Has for Years)", excerpt: "Iceland generates all of its electricity from geothermal and hydro. No solar panels, no wind farms — just volcanoes.", body: "Iceland runs its entire electricity grid on renewable energy — approximately 70% hydroelectric and 30% geothermal, with the geothermal component growing every year. The country sits atop the Mid-Atlantic Ridge, where the North American and Eurasian tectonic plates diverge, producing intense volcanic activity. This isn't just free energy — it's essentially unlimited. The Hellisheiði Power Station alone produces 303 MW of electricity and 400 MW of thermal energy for heating. Every home in Reykjavík is heated by geothermal water piped directly from the ground. The country exports aluminum (an extremely energy-intensive metal to produce) specifically because it can offer smelters virtually unlimited cheap green electricity. The catch? Iceland's population is only 370,000 — the size of a mid-sized American city. Scaling this model globally requires either massive geothermal resources or different solutions entirely. But as a proof of concept, Iceland stands alone.", category: 'science', emoji: '🌋', country: 'Iceland', readTime: 5, imageGradient: 'from-green-600/20 to-teal-600/20' },
  { title: "The Bizarre Tradition of Cheese Rolling in the English Countryside", excerpt: "Once a year, hundreds of people chase a 9-pound cheese wheel down a near-vertical hill. It's been happening for 200 years.", body: "Cooper's Hill Cheese-Rolling and Wake is held annually on the last Monday of May at Cooper's Hill near Gloucester, England. The rules are simple: a 9-pound round of Double Gloucester cheese is rolled down a nearly vertical 200-meter hill. Competitors chase it. The first person to the bottom wins the cheese. The cheese can reach speeds of 70 mph — faster than any human — so nobody actually catches it; you just have to get down the hill first. The event has no official organizer, no sponsors, and no safety nets beyond St. John Ambulance volunteers stationed at the bottom who treat the inevitable injuries. An average year sees 15–20 people carted off with sprains and fractures. The cheese has been replaced with a foam replica in some years after animal rights concerns about the real cheese flying uncontrolled into crowds. Despite being officially 'cancelled' multiple times by local authorities, it always happens anyway.", category: 'weird', emoji: '🧀', country: 'UK', readTime: 4, imageGradient: 'from-yellow-600/20 to-amber-600/20' },
  { title: "How Bali Runs on a 210-Day Year", excerpt: "While the rest of the world uses a 365-day Gregorian calendar, Bali's traditional Pawukon calendar completes a full year in just 210 days.", body: "Bali operates on two simultaneous calendar systems. The Gregorian calendar governs commerce and government — but daily spiritual and social life runs on the Pawukon calendar, a 210-day ceremonial cycle with no months, only seven interlocking 'weeks' of different lengths running simultaneously (from a 1-day week to a 10-day week). The intersection of these weeks determines the spiritual quality of each day. Certain days are sacred for opening businesses, others for weddings, others for specific deities. Because 210 doesn't divide evenly into 365, the same Balinese holy day occurs on different Gregorian dates each year, giving Bali one of the densest festival calendars on Earth — some years see over 240 official ceremony days. The Ogoh-Ogoh parade before Nyepi (Bali's 'Day of Silence') is one result: an enormous festival followed by a complete island blackout where even the airport closes for 24 hours.", category: 'culture', emoji: '🌺', country: 'Indonesia', readTime: 5, imageGradient: 'from-fuchsia-500/20 to-pink-600/20' },
  { title: "The GPS Satellites Are Traveling So Fast, Your Phone Needs Relativity to Work", excerpt: "Without Einstein's theory of relativity, GPS would drift by 11km every day. Here's the mind-bending physics your phone silently runs.", body: "Every GPS satellite orbits at about 20,200 km altitude, traveling at 14,000 km/h. At this speed and altitude, two relativistic effects fight each other inside the satellite's atomic clocks. Special relativity (caused by velocity) makes satellite clocks run slightly slower than ground clocks — by 7 microseconds per day. General relativity (caused by weaker gravity at altitude) makes them run faster — by 45 microseconds per day. The net effect: GPS clocks run 38 microseconds fast per day relative to your phone. That sounds tiny. But GPS works by measuring signal travel time to the nanosecond — at the speed of light, 38 microseconds of error equals 11 kilometers of positional drift per day. So every GPS satellite has its atomic clock pre-adjusted before launch to compensate — set to run slightly slow — and software corrections run continuously. Without Einstein, written in 1905 and 1915, your Uber driver would be 11km off by tomorrow morning.", category: 'science', emoji: '🛰️', readTime: 6, imageGradient: 'from-violet-500/20 to-purple-600/20' },
// CULTURE - extras (need 2 more for 5 total)
  { title: "The Country Where Everyone Naps at Work — By Law", excerpt: "In Japan, 'inemuri' — sleeping on the job — is not just tolerated. It's a sign of hard work. Here's the fascinating cultural logic.", body: "In most of the world, being caught napping at your desk would end your career. In Japan, the practice of inemuri — literally 'sleeping while present' — is interpreted as evidence that you worked so hard you exhausted yourself. It's a form of social proof. Surveys show 40% of Japanese adults regularly practice inemuri at work, in meetings, even on the commute. The rules are unspoken but consistent: you must maintain a posture that suggests you could snap back to attention at any moment. Slumping fully is bad form; a chin-on-chest nod is acceptable. This cultural norm aligns with Japan's well-documented sleep deficit — the Japanese average 6.5 hours per night, among the lowest of any developed nation. Inemuri fills the gap, and productivity studies suggest it actually works: a 10-20 minute nap has been shown to restore alertness more effectively than caffeine. Companies like Panasonic have started installing dedicated nap pods. The West calls it power-napping. Japan just always knew.", category: 'culture', emoji: '😴', country: 'Japan', readTime: 4, imageGradient: 'from-indigo-500/20 to-blue-600/20' },
  { title: "Finland Has 2 Million Saunas for 5.5 Million People", excerpt: "That's almost one sauna per household. In Finland, the sauna isn't a luxury — it's the center of social life.", body: "Finland has approximately 2 million saunas for a population of 5.5 million people — meaning families often have one at home, and every apartment building has a shared one. The sauna predates the house for many Finnish families: historically, the first thing built on a plot of land was a sauna, which served as a birthing room, a healing space, and a place to prepare the dead. Modern Finnish saunas run at 80-100°C and involve throwing water on hot stones (löyly) to create steam. Business deals are negotiated in saunas. Diplomacy happens there. The Finnish parliament has a sauna. Mobile phones are banned — it's one of the last true neutral spaces. UNESCO added Finnish sauna culture to its Intangible Cultural Heritage list in 2020. Finns consider it rude to discuss serious or stressful topics in the sauna — the heat is for relaxation, honesty, and equality. A Finnish saying: 'In the sauna, everyone is equal.'", category: 'culture', emoji: '🧖', country: 'Finland', readTime: 4, imageGradient: 'from-cyan-600/20 to-teal-500/20' },

  // TRAVEL - extras (need 2 more)
  { title: "The Island That Appears and Disappears From Maps Every Few Years", excerpt: "Sandy Island was on maps for over a century. In 2012, a research ship sailed to its coordinates — and found open ocean.", body: "Sandy Island appeared on maps between Australia and New Caledonia for over a century. It showed up on Google Maps, on the official charts of multiple nations, and in scientific databases. In 2012, a research vessel from the University of Sydney sailed to its exact coordinates to survey it. They found nothing — 1,400 meters of open ocean. The island had never existed. The phantom island likely originated from a 19th-century whaling ship that reported a reef, and the sighting was copied from map to map for 137 years without anyone checking. When Google was notified, they removed it within a week. This isn't an isolated case: historical maps are littered with phantom islands, most originating from misread instruments, wishful thinking, or deliberate deception by captains who wanted to keep trade routes secret. The South Atlantic alone had over a dozen such islands that appeared and disappeared over centuries.", category: 'travel', emoji: '🏝️', readTime: 4, imageGradient: 'from-blue-500/20 to-teal-600/20' },
  { title: "The Only Place on Earth Where Four Countries Meet at One Point", excerpt: "At Kazungula in southern Africa, you can stand in Botswana, Zambia, Zimbabwe, and Namibia simultaneously.", body: "The Kazungula quadripoint sits at the junction of the Zambezi and Chobe rivers in southern Africa, where the borders of Botswana, Zambia, Zimbabwe, and Namibia theoretically converge at a single point. It is one of only two places on Earth where four countries share a border point (the other being the Four Corners monument in the US). The Kazungula Ferry crossing between Botswana and Zambia was, until 2021, one of the only ferry crossings to use a ferry as a border crossing between two countries that don't actually share a land border — they share only a point. In 2021, the Kazungula Bridge opened — a remarkable engineering project that had to navigate four countries' territorial claims and sovereignty interests simultaneously. For decades, the border was disputed: Zambia and Zimbabwe claimed the quadripoint didn't exist and that their borders touched, making the Kazungula crossing illegal. International courts eventually sided with Botswana and Namibia.", category: 'travel', emoji: '🌍', country: 'Africa', readTime: 5, imageGradient: 'from-amber-500/20 to-orange-500/20' },

  // SCIENCE - extras (need 2 more)
  { title: "The Experiment That Has Been Running Since 1927 and Won't Stop", excerpt: "A tar pitch funnel has been dripping since 1927 in an Australian lab. Only 10 drops in 97 years. Nobody has ever seen one fall.", body: "The Pitch Drop Experiment at the University of Queensland has been running continuously since 1927. Pitch — a form of solidified tar — looks and feels like a solid, but is actually an extremely viscous liquid. A funnel was filled with pitch and left to drip at room temperature. Since 1927, approximately 10 drops have formed and fallen. The average time between drops is about 10 years. The experiment is in the Guinness Book of Records as the world's longest-running lab experiment. The remarkable thing? Despite being continuously watched since the internet made it possible to livestream in the 1990s, nobody has ever witnessed a drop fall live on camera. Drops tend to fall off-camera, during power cuts, or when the one person watching looks away. The experiment has outlived its original creator, Professor Thomas Parnell. A custodian physicist, Professor John Mainstone, watched the experiment for 52 years and died in 2013 having never seen a drop fall despite being in the room multiple times when one was imminent.", category: 'science', emoji: '🔬', country: 'Australia', readTime: 5, imageGradient: 'from-emerald-500/20 to-teal-500/20' },
  { title: "Why Dogs Can Smell Time — And What It Tells Us About Consciousness", excerpt: "A dog doesn't need a clock. They can tell how long you've been gone by how much your scent has faded. Science just proved it.", body: "Alexandra Horowitz, a dog cognition researcher at Columbia University, has documented that dogs experience time through smell — specifically through the rate at which scent molecules decay and disperse. When you leave the house, your scent concentration is high. As hours pass, molecules drift, settle, and break down. By the time you return, the strength and composition of your scent residue tells the dog approximately how long you've been gone. Dogs trained in her lab showed measurable differences in excited behavior depending on whether their owner had been gone 30 minutes versus 2 hours — triggered purely by odor concentration. This suggests dogs have a form of temporal memory tied entirely to sensory decay rather than an internal clock. It implies that different animals may experience time in fundamentally different ways — not as a shared universal experience, but as a species-specific construction. Some researchers believe this is a clue that consciousness itself, and the experience of time's passage, is not a single phenomenon but a family of related experiences unique to each type of mind.", category: 'science', emoji: '🐕', readTime: 5, imageGradient: 'from-violet-500/20 to-purple-600/20' },

  // TECH - extras (need 4 more to reach 5)
  { title: "The USB Plug That Takes 3 Tries to Insert — And Why It Was Designed That Way", excerpt: "USB-A is wrong 100% of the time on the first try, 50% on the second. This wasn't an accident. Here's the story.", body: "The USB Type-A connector — the rectangular one — has a design that seems intentionally cruel: it is asymmetric in a way that makes it nearly impossible to insert correctly on the first attempt. The joke goes that there are three orientations: wrong, wrong, and right. This wasn't incompetence. The original USB 1.0 design spec from 1996 specifically chose an asymmetric connector to prevent damage from forced reverse insertion. A symmetric connector could be forced in either way, potentially bending pins. The asymmetric design ensures one direction fails before any damage occurs. The real problem was that the asymmetry was too subtle — the top and bottom look nearly identical in low light. The designer, Ajay Bhatt (also the co-inventor of the USB standard), later acknowledged the indicator marking — a small logo on top — was added as a fix, but nobody noticed it. USB-C, the modern successor, is fully reversible and was specifically designed to solve this exact problem. Bhatt's team at Intel knew about the frustration by 1998 but were locked into manufacturing contracts.", category: 'tech', emoji: '🔌', readTime: 4, imageGradient: 'from-blue-600/20 to-indigo-600/20' },
  { title: "How Wikipedia Stays (Mostly) Accurate With Almost No Paid Staff", excerpt: "The 5th most visited website on Earth is run by ~50 employees. 60 million edits a year come from volunteers. The system is weirder than you think.", body: "Wikipedia has approximately 50 million articles across 300+ languages and receives over 1.7 billion unique visitors per month — making it the 5th most visited website on Earth. The Wikimedia Foundation that runs it employs only about 700 people total, of whom perhaps 50 work on content. The rest of the work — 60 million edits per year — comes from an estimated 280,000 active volunteer editors. How does accuracy hold up? Through an elaborate reputation system, bot enforcement, and a culture of obsessive citation. Wikipedia bots automatically revert obvious vandalism within seconds — a study found median vandalism lifespan of 1.7 minutes. Human editors specializing in particular topics police their areas fiercely. The real quality problem isn't vandalism — it's systematic bias in who edits. Studies show ~90% of Wikipedia editors are male, predominantly from the US and Europe, leading to well-documented gaps: female scientists are underrepresented, and non-Western topics have shallower coverage. Wikipedia's leadership knows this and has been running diversity programs since 2011 with limited success.", category: 'tech', emoji: '📖', readTime: 5, imageGradient: 'from-gray-500/20 to-slate-600/20' },
  { title: "The Algorithm That Runs 35% of the Internet — Written by One Person in 1994", excerpt: "Rasmus Lerdorf wrote PHP over a weekend to track visits to his resume. It now powers WordPress, Wikipedia, and most of the web.", body: "PHP was created in 1994 by Rasmus Lerdorf — a Danish-Canadian programmer who wanted to track visitors to his online resume. He wrote a set of CGI scripts in C, called them 'Personal Home Page Tools,' and posted them online. Within months, thousands of people were using them. Lerdorf added database connectivity and called the whole thing a 'form interface' — PHP/FI. He has said publicly that he never intended to create a programming language: 'I don't know how to stop it. I never did. There was never any intention to write a programming language. I absolutely have no idea how to write a programming language, I just kept adding the next logical step.' PHP now runs approximately 77% of all websites with a known server-side language, including 43% of all websites via WordPress. Facebook ran on PHP until 2010 (and created HipHop, a PHP-to-C++ compiler, just to make it fast enough). Wikipedia runs PHP. The irony is that PHP is widely criticized by professional programmers for inconsistent design — yet it quietly powers a third of human civilization's digital infrastructure.", category: 'tech', emoji: '💻', readTime: 5, imageGradient: 'from-purple-500/20 to-pink-500/20' },
  { title: "The Internet Has 3 Physical Choke Points That Could Break Everything", excerpt: "95% of global internet traffic passes through underwater cables. A few key spots could — and occasionally do — take down entire continents.", body: "The global internet feels wireless and distributed, but 95% of intercontinental data travels through about 400 submarine cables — physical fiber-optic lines lying on the ocean floor. These cables are roughly the width of a garden hose and carry petabits of data per second. They have surprisingly few points of failure. The Luzon Strait between Taiwan and the Philippines carries the densest cable concentration in the world — cables serving East Asia, Southeast Asia, and the US all converge here. In 2006, an earthquake severed seven cables simultaneously, knocking out 90% of Taiwan's internet capacity and slowing connectivity across Asia for weeks. The Egyptian coast is another critical chokepoint: almost all cables connecting Europe to Asia pass through the Suez Canal area. In 2022, a ship anchor cut three cables off Alexandria, disrupting connectivity across multiple African countries. And the GIUK Gap (Greenland-Iceland-UK) carries most transatlantic traffic. These cables are largely unguarded, lying in international waters. A 2023 NATO report identified submarine cable infrastructure as one of the most critical and most vulnerable points of modern civilization.", category: 'tech', emoji: '🌐', readTime: 6, imageGradient: 'from-cyan-600/20 to-blue-700/20' },

  // WEIRD - extras (need 2 more)
  { title: "There's a Town in Norway Called Hell — And It Freezes Over Every Winter", excerpt: "The phrase 'when hell freezes over' hits differently when you're in Hell, Norway, watching the temperature drop below -20°C.", body: "Hell is a small village in Stjørdal municipality in central Norway. Population: about 1,600. Average January temperature: around -5°C, sometimes reaching -20°C. The town name derives from the Old Norse word 'hellir,' meaning 'overhang' or 'cliff cave' — nothing to do with the underworld. Doesn't stop the locals from leaning into it. The town's train station sign (HELL) is one of the most photographed in Norway. There's a blues festival called 'Hell Freezes Over.' The goods warehouse was called 'Gods Ekspedisjon' in Norwegian — which translates directly to 'God's Expedition' but was often misread by English-speaking visitors as 'Gods Expedition,' implying divine cargo. The town took it in stride and made it a tourist attraction. Hell also exports: the phrase 'hell freezes over' actually originated independently from the theology of permanent damnation — but Hell, Norway proved it literally happens every January, which locals find endlessly amusing.", category: 'weird', emoji: '🥶', country: 'Norway', readTime: 3, imageGradient: 'from-blue-700/20 to-indigo-500/20' },
  { title: "The Country That Accidentally Declared War on Itself", excerpt: "In 1788, the Austrian army fought itself in the Battle of Karánsebes. Thousands of casualties. No enemy involved.", body: "The Battle of Karánsebes in 1788 is one of history's most remarkable military disasters. The Austrian army, camped near the town of Karánsebes in modern Romania, was waiting to fight the Ottoman Empire. A group of hussars (cavalry) found local merchants selling schnapps and started drinking. Infantry soldiers arrived and demanded alcohol too. A fight broke out between the hussars and infantry. Someone shouted 'Turci!' (Turks!). Panic spread. In the darkness, units couldn't identify each other. Soldiers began firing on what they assumed were Ottoman forces. The chaos spread through the entire 100,000-man army. Officers tried to restore order but were ignored or attacked. By dawn, the Austrian army had retreated — two days before the Ottomans even arrived. The Ottomans found a battlefield littered with approximately 10,000 Austrian casualties (killed, wounded, or captured in the confusion) and simply walked in. Emperor Joseph II of Austria was knocked off his horse by panicking troops during the incident. Historians still debate the exact details, but primary sources confirm the broad outline: the Austrian army defeated itself.", category: 'weird', emoji: '⚔️', country: 'Austria', readTime: 5, imageGradient: 'from-orange-600/20 to-red-600/20' },

  // HISTORY - extras (need 2 more)
  { title: "The Letter That Prevented World War III — Typed on a 1960s Teletype Machine", excerpt: "On October 27, 1962, a single message from a Soviet submarine officer prevented a nuclear launch. Nobody knew about it for 40 years.", body: "On October 27, 1962 — the most dangerous day of the Cuban Missile Crisis — a Soviet submarine designated B-59 was being depth-charged by US Navy ships trying to force it to surface. The submarine had lost radio contact with Moscow for days. The captain, Valentin Savitsky, believed World War III had already begun. The B-59 was armed with a nuclear torpedo with a yield comparable to the Hiroshima bomb. Soviet protocol at the time required agreement from three officers to authorize a nuclear launch: the captain, the political officer, and the flotilla commander — who happened to be on board. Captain Savitsky and the political officer both agreed to launch. The third officer, Vasili Arkhipov, refused. His refusal prevented the launch. The submarine surfaced. The crisis deescalated. Arkhipov's role wasn't declassified until 2002. When the story became public at a 2002 conference in Havana, former Secretary of Defense Robert McNamara — who had been in the room with JFK during the crisis — said simply: 'We came that close to nuclear war. The guy who saved the world — Vasili Arkhipov.'", category: 'history', emoji: '🚢', country: 'Russia', readTime: 6, imageGradient: 'from-red-600/20 to-rose-500/20' },
  { title: "The Ancient Roman Shopping Mall That's Still Standing After 2,000 Years", excerpt: "Trajan's Market in Rome, built around 110 AD, had 150 shops on six levels selling everything from spices to government grain.", body: "Trajan's Market in Rome, completed around 110 AD under Emperor Trajan, is widely considered the world's first shopping mall. The complex comprised six levels built into the Quirinal Hill, containing approximately 150 individual shop units arranged in a hemicycle facing the Forum of Trajan. The ground floor tabernae (shops) sold wine, olive oil, and exotic goods imported from across the empire. Upper floors handled grain distribution — a government welfare program that fed tens of thousands of Romans daily. The top floors may have housed administrative offices. The complex was architecturally revolutionary: it used concrete vaulted ceilings, a covered main street (the Via Biberatica), and heated indoor spaces — innovations that wouldn't reappear in commercial architecture for over a thousand years. The building survived the fall of the Roman Empire, medieval fortification (it became a castle), Renaissance renovations, and two World Wars. You can walk through most of it today, admission 15 euros, and the Via Biberatica still looks uncannily like a modern outdoor mall street.", category: 'history', emoji: '🏛️', country: 'Italy', readTime: 5, imageGradient: 'from-amber-600/20 to-yellow-500/20' },
    { title: "The Amazon River Has No Bridges Across It — For Its Entire 6,400km Length", excerpt: "The world's largest river by volume flows through one of the most biodiverse ecosystems on Earth, and not a single bridge spans it.", body: "The Amazon River stretches 6,400 kilometers across South America and carries 20% of all the freshwater that flows into the world's oceans. Despite this immense scale — and Brazil's status as a major economy — not one bridge crosses the main Amazon River. The reasons are multiple: the river floods dramatically each year (water levels vary by up to 10 meters seasonally), creating constantly shifting floodplains that make foundations unstable. The jungle on either side has almost no roads, so a bridge would connect nothing to nothing. The Amazon is the highway — a network of riverboats serves as the primary transportation infrastructure for millions of people in riverside communities. Ferries and small aircraft handle cross-river travel. Some Amazon tributaries have bridges — Manaus has a bridge over the Rio Negro — but the main river itself remains unbridged, one of the most remarkable infrastructure facts about any major world river.", category: 'travel', emoji: '🌊', country: 'Brazil', readTime: 5, imageGradient: 'from-emerald-500/20 to-green-600/20' },
];

// Deterministic shuffle based on a seed (hour-based)
function seededShuffle<T>(arr: T[], seed: number): T[] {
  const a = [...arr];
  let s = seed;
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    const j = Math.abs(s) % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function generatePosts(seed: number): BlogPost[] {
  const shuffled = seededShuffle(BLOG_POOL, seed);
  const now = Date.now();
  return shuffled.map((p, i) => ({
    ...p,
    id: `${seed}-${i}`,
    publishedAt: now - i * 18 * 60 * 1000,
  }));
}

interface BlogStore {
  posts: BlogPost[];
  lastRefreshed: number;
  currentSeed: number;
  refreshPosts: (manual?: boolean) => void;
  initPosts: () => void;
}

export const useBlogStore = create<BlogStore>()(
  persist<BlogStore>(
    (set, get) => ({
      posts: [],
      lastRefreshed: 0,
      currentSeed: 0,

      initPosts: () => {
        const { lastRefreshed, refreshPosts } = get();
        const TWO_HOURS = 2 * 60 * 60 * 1000;
        if (Date.now() - lastRefreshed > TWO_HOURS || !lastRefreshed) {
          refreshPosts();
        }
      },

      refreshPosts: (manual = false) => {
        // manual refresh gets a truly random seed; auto-refresh uses time-based seed
        const seed = manual
          ? Math.floor(Math.random() * 0x7fffffff)
          : Math.floor(Date.now() / (2 * 60 * 60 * 1000));
        set({ posts: generatePosts(seed), lastRefreshed: manual ? get().lastRefreshed : Date.now(), currentSeed: seed });
      },
    }),
    {
      name: 'blog-store-v1',
      partialize: (state: BlogStore) => ({ posts: state.posts, lastRefreshed: state.lastRefreshed, currentSeed: state.currentSeed } as BlogStore),
    },
  ),
);
