import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  body: string;
  category: 'culture' | 'science' | 'travel' | 'history' | 'weird' | 'tech';
  emoji: string;
  country?: string;
  readTime: number; // minutes
  publishedAt: number; // timestamp
  imageGradient: string;
}

const BLOG_POOL: Omit<BlogPost, 'id' | 'publishedAt'>[] = [
  { title: "Why Japan Has 3 Different Alphabets (And Uses All of Them at Once)", excerpt: "Hiragana, katakana, kanji — and sometimes romaji too. Here's why Japanese text looks like a beautiful puzzle.", body: "Japanese is unique in that it actively uses three different writing systems simultaneously — and often in the same sentence. Hiragana (ひらがな) handles native Japanese words and grammar. Katakana (カタカナ) is reserved for foreign loanwords and emphasis, while kanji (漢字) are Chinese-derived characters that carry meaning. A single menu at a Tokyo ramen shop might include all three in three words. The system evolved over centuries: kanji arrived via China, hiragana was developed by women in the Heian period as a more fluid script, and katakana was created by Buddhist monks. Far from being confusing, Japanese readers process all three automatically — a feat of cognitive flexibility that amazes linguists worldwide.", category: 'culture', emoji: '🇯🇵', country: 'Japan', readTime: 4, imageGradient: 'from-red-500/20 to-pink-600/20' },
  { title: "The Midnight Sun: Where the Sun Never Sets for 70 Days Straight", excerpt: "In northern Norway, the sun stays above the horizon for over two months. Here's what life is actually like.", body: "Above the Arctic Circle in places like Tromsø, Norway, the midnight sun is real — from late May to late July the sun simply doesn't go down. At 2am you can read a book outside without a lamp. Birds sing at midnight. Children play football at 11pm. The phenomenon is caused by Earth's axial tilt of 23.5 degrees: in summer, the North Pole tilts toward the sun so dramatically that polar regions receive continuous sunlight. Locals adapt with blackout curtains, sleep masks, and a relaxed attitude toward conventional sleeping hours. The flip side? In winter, these same towns experience polar night — no sun at all for weeks. The Sami people, indigenous to the region, have adapted culturally over millennia and have dozens of words for different types of Arctic light.", category: 'travel', emoji: '🌅', country: 'Norway', readTime: 5, imageGradient: 'from-orange-500/20 to-yellow-500/20' },
  { title: "The Town That Lives in a Permanent Time Paradox", excerpt: "Lijiang, China exists in a single timezone despite spanning the width of a continent. The result? Sunrise at 10am.", body: "China is geographically wide enough to span five natural time zones — from UTC+5 to UTC+9. But in 1949, the People's Republic decided to unify the entire country under a single timezone: Beijing Time (UTC+8). The result in western provinces like Xinjiang is surreal: the sun rises at 10am and sets past 10pm in summer. Office hours have quietly shifted — people eat lunch at 2pm and dinner at 9pm. In Xinjiang, the Uyghur minority often run on an unofficial 'Xinjiang time' two hours behind Beijing, creating a dual-timezone reality within the same city. This isn't unique to China — India uses one timezone too, creating a 90-minute offset at its western and eastern extremes. Time, it turns out, is deeply political.", category: 'weird', emoji: '⏰', country: 'China', readTime: 4, imageGradient: 'from-cyan-500/20 to-blue-600/20' },
  { title: "How Polynesians Navigated the Pacific With No Instruments", excerpt: "No compass, no GPS, no maps. Just stars, waves, and birds — and they found every island in the Pacific.", body: "The Polynesian voyagers who settled islands across 10 million square miles of the Pacific Ocean did so with a navigation system so sophisticated it still amazes scientists. Wayfinders read the stars — memorizing the rising and setting positions of hundreds of stars to construct a mental star compass. They felt the ocean swells with their bodies, detecting how major swells wrap around islands, creating 'swell shadows' detectable hundreds of miles away. Birds were tracked: certain species fly up to 40 miles from land each morning and return each evening, serving as living compasses. The shape of clouds, the color of water, and even the smell of vegetation guided them. This knowledge, nearly lost in the 20th century, is being actively revived by organizations like the Polynesian Voyaging Society, whose canoe Hōkūleʻa has circumnavigated the globe using only traditional navigation.", category: 'history', emoji: '🧭', country: 'Polynesia', readTime: 6, imageGradient: 'from-teal-500/20 to-cyan-600/20' },
  { title: "The Weird Science of Why 3pm Feels Slower Than 3am", excerpt: "Your brain literally experiences time differently depending on the hour — and science finally knows why.", body: "Time perception is not constant — your brain actively constructs the experience of time passing, and it does so differently depending on circadian phase, emotion, temperature, and even what you're doing. In the early afternoon, body temperature peaks and the brain's clock neurons fire most rapidly, making time feel like it drags. At 3am, when body temperature is at its lowest, subjective time collapses — minutes vanish. The dopamine system plays a huge role: when you're excited or deeply focused, dopamine causes internal clock pulses to speed up, making you underestimate elapsed time ('flow state'). Fear does the opposite — it slows perceived time, which is why near-misses seem to happen in slow motion. This isn't just psychological: different countries' work cultures exploit these rhythms naturally. Spain's siesta tradition, Japan's inemuri (socially acceptable public napping), and Scandinavia's early work start times are all aligned, consciously or not, with human chronobiology.", category: 'science', emoji: '🧠', country: undefined, readTime: 5, imageGradient: 'from-purple-500/20 to-indigo-600/20' },
  { title: "Iceland Has No Mosquitoes — Here's the Bizarre Reason Why", excerpt: "It's cold, it's wet, it has plenty of standing water. Mosquitoes should love it. But there are none. Science is baffled.", body: "Iceland is a mosquito-free paradise — a fact that seems impossible given that mosquitoes thrive in cold, wet environments across Scandinavia, Canada, and Russia, all of which share Iceland's climate. The leading theory involves Iceland's freeze-thaw cycles: mosquito larvae need consistently cold water that freezes and thaws on a predictable seasonal schedule to complete their life cycle. Iceland's weather is unusually variable even within a single season, disrupting larval development. A warm week in February can hatch larvae that then die in a March freeze. Another theory involves Iceland's unique geothermal activity — the water chemistry in naturally heated pools may be inhospitable to larvae. Whatever the reason, Icelanders enjoy outdoor summers blissfully free of the swarms that plague every neighboring country. Several other places share this status: the Faroe Islands, New Caledonia, and French Polynesia.", category: 'weird', emoji: '🦟', country: 'Iceland', readTime: 3, imageGradient: 'from-blue-500/20 to-cyan-500/20' },
  { title: "The Country That Invented the Weekend — And How It Spread to the World", excerpt: "The 5-day workweek isn't ancient wisdom. It was invented in 1908 in a New England cotton mill. Here's the full story.", body: "The modern weekend as we know it — two full days off on Saturday and Sunday — is surprisingly recent. Before the 20th century, the typical worker had only Sunday off, if that. The shift began in 1908 at a cotton mill in New England that wanted to accommodate its Jewish workers, who observed the Sabbath on Saturday. By giving Saturday off as well as Sunday, the mill inadvertently created the first secular two-day weekend. Henry Ford institutionalized it in 1926 when he switched Ford Motor Company to a 40-hour, 5-day work week — not out of generosity, but because he believed workers with leisure time would spend money on cars and consumer goods. The Great Depression pushed governments to codify the 40-hour week through legislation as a way to spread employment. The international labor organization standardized it globally by mid-century. Today, some countries are experimenting with 4-day weeks — the next evolution in a surprisingly short 116-year history.", category: 'history', emoji: '🎉', country: 'USA', readTime: 5, imageGradient: 'from-green-500/20 to-emerald-600/20' },
  { title: "Dubai Built an Indoor Ski Slope in the Desert — And It's Busier Than Most Mountain Resorts", excerpt: "Ski Dubai sits inside a mall in one of the hottest cities on Earth. 400 real tons of snow, real penguins, and 6,000 visitors a day.", body: "Ski Dubai opened in 2005 inside the Mall of the Emirates in a city where outdoor temperatures regularly hit 45°C (113°F). The facility maintains an indoor temperature of -1°C to -2°C year-round, houses five ski runs including a 400-meter black diamond slope, and uses real snow — about 30 tons of which are produced each night by snow cannon systems. The penguins (real South African penguins) live in a dedicated sub-zero habitat and come out to meet visitors twice daily. The facility uses roughly the same amount of energy as 1,500 homes — a fact that draws both admiration and criticism. But it's commercially successful: it attracts over 6,000 visitors on peak days and has inspired copycat indoor ski resorts across the Middle East and China. It's also bizarrely functional: Dubai's ski instructors are legitimately certified European coaches who moved to the desert for steady year-round work.", category: 'travel', emoji: '⛷️', country: 'UAE', readTime: 4, imageGradient: 'from-sky-500/20 to-blue-600/20' },
  { title: "The Voynich Manuscript: The 600-Year-Old Book Nobody Can Read", excerpt: "Discovered in 1912, carbon-dated to 1404, filled with mysterious illustrations and an unknown language. Still undeciphered.", body: "The Voynich Manuscript is a 240-page illustrated codex written in an unknown script that has defeated some of the world's best cryptographers, linguists, and AI systems for over a century. Carbon dating places its creation between 1404 and 1438. The illustrations depict unidentifiable plants, naked women in green pools connected by tubes, astronomical diagrams, and zodiac-like charts — all accompanied by flowing text in a script that has never been seen in any other document. It follows the statistical patterns of a real language (Zipf's Law, character frequency distributions) yet no one has ever matched it to any known or proposed language. The manuscript was purchased in 1912 by book dealer Wilfrid Voynich from an Italian castle. Theories range from an elaborate hoax to an extinct language to an alien document. In 2019, a Bristol academic claimed it was written in proto-Romance phonetic script — but the claim was swiftly disputed. It remains the most mysterious manuscript in existence.", category: 'history', emoji: '📜', readTime: 6, imageGradient: 'from-amber-500/20 to-orange-600/20' },
  { title: "Why South Korea Has the World's Fastest Internet — And How They Built It", excerpt: "Average speeds 10x faster than the US. It was a government decision made in 1994, and it changed everything.", body: "South Korea consistently tops global internet speed rankings — average download speeds exceed 250 Mbps, with many homes on gigabit fiber. The US averages around 230 Mbps, but Korea's consistency is the real achievement: 99.9% of the population has access to high-speed broadband. The story starts in 1994 when President Kim Young-sam declared the 'Information Superhighway' a national priority. The government subsidized fiber rollout and forced telecom competition by opening local loops to multiple providers. Crucially, Korea's high urban population density made fiber economics work: running a cable in Seoul reaches 20,000 households per kilometer vs. 200 in rural America. The cultural side helped too: PC bangs (internet cafés) created a national gaming culture in the late 1990s that demanded fast, reliable internet, which drove consumer expectations sky-high. The result is infrastructure that handles 8K streaming, real-time cloud gaming, and remote surgery with ease.", category: 'tech', emoji: '⚡', country: 'South Korea', readTime: 5, imageGradient: 'from-rose-500/20 to-pink-600/20' },
  { title: "The Country That Runs on 100% Renewable Energy (And Has for Years)", excerpt: "Iceland generates all of its electricity from geothermal and hydro. No solar panels, no wind farms — just volcanoes.", body: "Iceland runs its entire electricity grid on renewable energy — approximately 70% hydroelectric and 30% geothermal, with the geothermal component growing every year. The country sits atop the Mid-Atlantic Ridge, where the North American and Eurasian tectonic plates diverge, producing intense volcanic activity. This isn't just free energy — it's essentially unlimited. The Hellisheiði Power Station alone produces 303 MW of electricity and 400 MW of thermal energy for heating. Every home in Reykjavík is heated by geothermal water piped directly from the ground. The country exports aluminum (an extremely energy-intensive metal to produce) specifically because it can offer smelters virtually unlimited cheap green electricity. The catch? Iceland's population is only 370,000 — the size of a mid-sized American city. Scaling this model globally requires either massive geothermal resources or different solutions entirely. But as a proof of concept, Iceland stands alone.", category: 'science', emoji: '🌋', country: 'Iceland', readTime: 5, imageGradient: 'from-green-600/20 to-teal-600/20' },
  { title: "The Bizarre Tradition of Cheese Rolling in the English Countryside", excerpt: "Once a year, hundreds of people chase a 9-pound cheese wheel down a near-vertical hill. It's been happening for 200 years.", body: "Cooper's Hill Cheese-Rolling and Wake is held annually on the last Monday of May at Cooper's Hill near Gloucester, England. The rules are simple: a 9-pound round of Double Gloucester cheese is rolled down a nearly vertical 200-meter hill. Competitors chase it. The first person to the bottom wins the cheese. The cheese can reach speeds of 70 mph — faster than any human — so nobody actually catches it; you just have to get down the hill first. The event has no official organizer, no sponsors, and no safety nets beyond St. John Ambulance volunteers stationed at the bottom who treat the inevitable injuries. An average year sees 15–20 people carted off with sprains and fractures. The cheese has been replaced with a foam replica in some years after animal rights concerns about the real cheese flying uncontrolled into crowds. Despite being officially 'cancelled' multiple times by local authorities, it always happens anyway.", category: 'weird', emoji: '🧀', country: 'UK', readTime: 4, imageGradient: 'from-yellow-600/20 to-amber-600/20' },
  { title: "How Bali Runs on a 210-Day Year", excerpt: "While the rest of the world uses a 365-day Gregorian calendar, Bali's traditional Pawukon calendar completes a full year in just 210 days.", body: "Bali operates on two simultaneous calendar systems. The Gregorian calendar governs commerce and government — but daily spiritual and social life runs on the Pawukon calendar, a 210-day ceremonial cycle with no months, only seven interlocking 'weeks' of different lengths running simultaneously (from a 1-day week to a 10-day week). The intersection of these weeks determines the spiritual quality of each day. Certain days are sacred for opening businesses, others for weddings, others for specific deities. Because 210 doesn't divide evenly into 365, the same Balinese holy day occurs on different Gregorian dates each year, giving Bali one of the densest festival calendars on Earth — some years see over 240 official ceremony days. The Ogoh-Ogoh parade before Nyepi (Bali's 'Day of Silence') is one result: an enormous festival followed by a complete island blackout where even the airport closes for 24 hours.", category: 'culture', emoji: '🌺', country: 'Indonesia', readTime: 5, imageGradient: 'from-fuchsia-500/20 to-pink-600/20' },
  { title: "The GPS Satellites Are Traveling So Fast, Your Phone Needs Relativity to Work", excerpt: "Without Einstein's theory of relativity, GPS would drift by 11km every day. Here's the mind-bending physics your phone silently runs.", body: "Every GPS satellite orbits at about 20,200 km altitude, traveling at 14,000 km/h. At this speed and altitude, two relativistic effects fight each other inside the satellite's atomic clocks. Special relativity (caused by velocity) makes satellite clocks run slightly slower than ground clocks — by 7 microseconds per day. General relativity (caused by weaker gravity at altitude) makes them run faster — by 45 microseconds per day. The net effect: GPS clocks run 38 microseconds fast per day relative to your phone. That sounds tiny. But GPS works by measuring signal travel time to the nanosecond — at the speed of light, 38 microseconds of error equals 11 kilometers of positional drift per day. So every GPS satellite has its atomic clock pre-adjusted before launch to compensate — set to run slightly slow — and software corrections run continuously. Without Einstein, written in 1905 and 1915, your Uber driver would be 11km off by tomorrow morning.", category: 'science', emoji: '🛰️', readTime: 6, imageGradient: 'from-violet-500/20 to-purple-600/20' },
  { title: "The Amazon River Has No Bridges Across It — For Its Entire 6,400km Length", excerpt: "The world's largest river by volume flows through one of the most biodiverse ecosystems on Earth, and not a single bridge spans it.", body: "The Amazon River stretches 6,400 kilometers across South America and carries 20% of all the freshwater that flows into the world's oceans. Despite this immense scale — and Brazil's status as a major economy — not one bridge crosses the main Amazon River. The reasons are multiple: the river floods dramatically each year (water levels vary by up to 10 meters seasonally), creating constantly shifting floodplains that make foundations unstable. The jungle on either side has almost no roads, so a bridge would connect nothing to nothing. The Amazon is the highway — a network of riverboats serves as the primary transportation infrastructure for millions of people in riverside communities. Ferries and small aircraft handle cross-river travel. Some Amazon tributaries have bridges — Manaus has a bridge over the Rio Negro — but the main river itself remains unbridged, one of the most remarkable infrastructure facts about any major world river.", category: 'travel', emoji: '🌊', country: 'Brazil', readTime: 5, imageGradient: 'from-emerald-500/20 to-green-600/20' },
];

// Deterministic shuffle based on a seed (hour-based)
function seededShuffle<T>(arr: T[], seed: number): T[] {
  const a = [...arr];
  let s = seed;
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    const j = Math.abs(s) % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function generatePosts(seed: number): BlogPost[] {
  const shuffled = seededShuffle(BLOG_POOL, seed);
  const featured = shuffled.slice(0, 6);
  const now = Date.now();
  return featured.map((p, i) => ({
    ...p,
    id: `${seed}-${i}`,
    publishedAt: now - i * 22 * 60 * 1000, // stagger publish times
  }));
}

interface BlogStore {
  posts: BlogPost[];
  lastRefreshed: number;
  currentSeed: number;
  refreshPosts: () => void;
  initPosts: () => void;
}

export const useBlogStore = create<BlogStore>()(
  persist<BlogStore>(
    (set, get) => ({
      posts: [],
      lastRefreshed: 0,
      currentSeed: 0,

      initPosts: () => {
        const { lastRefreshed, refreshPosts } = get();
        const TWO_HOURS = 2 * 60 * 60 * 1000;
        if (Date.now() - lastRefreshed > TWO_HOURS || !lastRefreshed) {
          refreshPosts();
        }
      },

      refreshPosts: () => {
        const seed = Math.floor(Date.now() / (2 * 60 * 60 * 1000));
        set({ posts: generatePosts(seed), lastRefreshed: Date.now(), currentSeed: seed });
      },
    }),
    {
      name: 'blog-store-v1',
      partialize: (state: BlogStore) => ({ posts: state.posts, lastRefreshed: state.lastRefreshed, currentSeed: state.currentSeed } as BlogStore),
    },
  ),
);
